package com.kaoyu.laiagent;

import org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication(exclude = PgVectorStoreAutoConfiguration.class)
public class LAiAgentApplication {
    public static void main(String[] args) {
        SpringApplication.run(LAiAgentApplication.class, args);
    }
}
